version: "3.9"
services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pds
      - POSTGRES_USER=pds
      - POSTGRES_PASSWORD=pds

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  emulator:
    image: gcr.io/flow-container-registry/emulator:0.31.1-sc2
    restart: unless-stopped
    command: emulator
    ports:
      - "3569:3569"
    env_file:
      - ./.env
    environment:
      - FLOW_SERVICEPRIVATEKEY=27f93302f5851077d63ece5b693094c0e5fc0a169369069fa8fb6a134ffc0eab
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
      - FLOW_PERSIST=true
      - FLOW_BLOCKTIME=0
