@distributionId = 00000000-0000-0000-0000-000000000000

### Create
POST  http://localhost:3000/v1/distributions HTTP/1.1
content-type: application/json

{
  "distId": 1,
  "issuer":"0x1",
  "meta": {
    "title": "Test",
    "description": "This is a test distribution",
    "image": "",
    "startDate": "2021-01-01T00:00:00Z",
    "endDate": "2021-01-01T00:00:00Z"
  },
  "packTemplate":{
    "packReference": {
      "name": "PackNFT",
      "address": "0x2"
    },
    "collectibleReference": {
      "name": "CollectibleNFT",
      "address": "0x3"
    },
    "packCount":2,
    "buckets": [
      {
        "collectibleCount": 3,
        "collectibleCollection": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      },
      {
        "collectibleCount": 2,
        "collectibleCollection": [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      }
    ]
  }
}

### List
GET http://localhost:3000/v1/distributions HTTP/1.1
content-type: application/json

### Get
GET http://localhost:3000/v1/distributions/{{ distributionId }} HTTP/1.1
content-type: application/json

### Settle
PUT http://localhost:3000/v1/distributions/{{ distributionId }}/settle HTTP/1.1
content-type: application/json

### Confirm
PUT http://localhost:3000/v1/distributions/{{ distributionId }}/confirm HTTP/1.1
content-type: application/json

### Cancel
DELETE  http://localhost:3000/v1/distributions/{{ distributionId }} HTTP/1.1
content-type: application/json
